package WssCalculator;


/**
* WssCalculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Thursday, 6 November, 2025 10:15:44 PM IST
*/

public interface CalcOperations 
{

  //Performs the Calculations:ADD/SUB/MUL/DIV
  int calculate (int _operator, int num1, int num2);

  //The Server EXITS when the Client prompts it to do so
  void shutdown ();
} // interface CalcOperations
