package FactorialApp;


/**
* FactorialApp/FactorialOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factorial.idl
* Thursday, 6 November, 2025 10:03:17 PM IST
*/

public interface FactorialOperations 
{
  int compute (int n);
} // interface FactorialOperations
