package FactorialApp;


/**
* FactorialApp/FactorialPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factorial.idl
* Thursday, 6 November, 2025 10:03:17 PM IST
*/

public abstract class FactorialPOA extends org.omg.PortableServer.Servant
 implements FactorialApp.FactorialOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("compute", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FactorialApp/Factorial/compute
       {
         int n = in.read_long ();
         int $result = (int)0;
         $result = this.compute (n);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FactorialApp/Factorial:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Factorial _this() 
  {
    return FactorialHelper.narrow(
    super._this_object());
  }

  public Factorial _this(org.omg.CORBA.ORB orb) 
  {
    return FactorialHelper.narrow(
    super._this_object(orb));
  }


} // class FactorialPOA
