package FactorialApp;

/**
* FactorialApp/FactorialHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factorial.idl
* Thursday, 6 November, 2025 10:03:17 PM IST
*/

public final class FactorialHolder implements org.omg.CORBA.portable.Streamable
{
  public FactorialApp.Factorial value = null;

  public FactorialHolder ()
  {
  }

  public FactorialHolder (FactorialApp.Factorial initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FactorialApp.FactorialHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FactorialApp.FactorialHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FactorialApp.FactorialHelper.type ();
  }

}
