package StringApp;


/**
* StringApp/StringOpsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from String.idl
* Thursday, 6 November, 2025 8:28:25 PM IST
*/

public abstract class StringOpsPOA extends org.omg.PortableServer.Servant
 implements StringApp.StringOpsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("reverse", new java.lang.Integer (0));
    _methods.put ("toUpper", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // StringApp/StringOps/reverse
       {
         String input = in.read_string ();
         String $result = null;
         $result = this.reverse (input);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // StringApp/StringOps/toUpper
       {
         String input = in.read_string ();
         String $result = null;
         $result = this.toUpper (input);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StringApp/StringOps:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public StringOps _this() 
  {
    return StringOpsHelper.narrow(
    super._this_object());
  }

  public StringOps _this(org.omg.CORBA.ORB orb) 
  {
    return StringOpsHelper.narrow(
    super._this_object(orb));
  }


} // class StringOpsPOA
