package StringApp;


/**
* StringApp/StringOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from String.idl
* Thursday, 6 November, 2025 8:28:25 PM IST
*/

public interface StringOpsOperations 
{
  String reverse (String input);
  String toUpper (String input);
} // interface StringOpsOperations
