package StringApp;

/**
* StringApp/StringOpsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from String.idl
* Thursday, 6 November, 2025 8:28:25 PM IST
*/

public final class StringOpsHolder implements org.omg.CORBA.portable.Streamable
{
  public StringApp.StringOps value = null;

  public StringOpsHolder ()
  {
  }

  public StringOpsHolder (StringApp.StringOps initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringApp.StringOpsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringApp.StringOpsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringApp.StringOpsHelper.type ();
  }

}
