package StringApp;


/**
* StringApp/StringOps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from String.idl
* Thursday, 6 November, 2025 8:28:25 PM IST
*/

public interface StringOps extends StringOpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOps
